---
name: CI

on:
  push:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running linter"
      - uses: https://github.com/marketplace/actions/super-linter

  Static_code_analysis_tests:
    runs-on: "ubuntu-latest"
    needs:
      - Lint
    steps:
      - run: echo "Runing static code analysis tests"