---
name: CI

on:
  push:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running linter"
      - uses: github/super-linter@v4

  Static-code-analysis-tests:
    runs-on: "ubuntu-latest"
    name: Static code analysis tests
    needs:
      - Lint
    steps:
      - run: echo "Runing static code analysis tests"
      - uses: actions/setup-python@v2g